event.list:
    path: /event
    methods: [GET]
    controller: App\Controller\EventController::eventListAction

event.single:
    path: /event/{eventId}
    methods: [GET]
    controller: App\Controller\EventController::singleEventAction

event.add:
    path: /event
    methods: [POST]
    controller: App\Controller\EventController::createEventAction
    condition: "request.isXmlHttpRequest()"
    
event.edit:
    path: /event
    methods: [PUT]
    controller: App\Controller\EventController::editEventAction
    
event.remove:
    path: /event/{eventId}
    methods: [DELETE]
    controller: App\Controller\EventController::removeEventAction
    

# event.single:
#   path: /event/{id}
#   methods: [GET]
#   controller: App\Controller\EventController::indexAction